export const SEND_FRIEND_REQUEST_START = 'SEND_FRIEND_REQUEST_START';
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';
export const SEND_FRIEND_REQUEST_FAIL = 'SEND_FRIEND_REQUEST_FAIL';

export const SEARCH_FOR_FRIEND_START = 'SEARCH_FOR_FRIEND_START';
export const SEARCH_FOR_FRIEND_SUCCESS = 'SEARCH_FOR_FRIEND_SUCCESS';
export const SEARCH_FOR_FRIEND_FAIL = 'SEARCH_FOR_FRIEND_FAIL';

export const START_FETCHING_FRIEND_REQUESTS = 'START_FETCHING_FRIEND_REQUESTS';
export const SUCCESS_FETCHING_FRIEND_REQUESTS = 'SUCCESS_FETCHING_FRIEND_REQUESTS';
export const FAIL_FETCHING_FRIEND_REQUESTS = 'FAIL_FETCHING_FRIEND_REQUESTS';

export const CONFIRM_FRIEND_REQUEST_SUCCESS = 'CONFIRM_FRIEND_REQUEST_SUCCESS';
export const CONFIRM_FRIEND_REQUEST_FAIL = 'CONFIRM_FRIEND_REQUEST_FAIL';

export const GET_ONLINE_FRIENDS_START = 'GET_ONLINE_FRIENDS_START';
export const GET_ONLINE_FRIENDS_SUCCESS = 'GET_ONLINE_FRIENDS_SUCCESS';
export const GET_ONLINE_FRIENDS_FAIL = 'GET_ONLINE_FRIENDS_FAIL';
