export const FOROGOT_PASSWORD_EMAIL_SEND_SUCCESS = 'FOROGOT_PASSWORD_EMAIL_SEND_SUCCESS';
export const FOROGOT_PASSWORD_EMAIL_SEND_FAIL = 'FOROGOT_PASSWORD_EMAIL_SEND_FAIL';
export const FOROGOT_PASSWORD_EMAIL_SEND_START = 'FOROGOT_PASSWORD_EMAIL_SEND_START';
