export const GET_USERS_PROFILE_PAGE_START = 'GET_USERS_PROFILE_PAGE_START';
export const GET_USERS_PROFILE_PAGE_SUCCESS = 'GET_USERS_PROFILE_PAGE_SUCCESS';
export const GET_USERS_PROFILE_PAGE_FAIL = 'GET_USERS_PROFILE_PAGE_FAIL';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILE = 'UPDATE_USER_FAILE';

export const LOAD_MORE_POSTS_REQUESTED_PROFILE_START = 'LOAD_MORE_POSTS_REQUESTED_PROFILE_START';
export const LOAD_MORE_POSTS_REQUESTED_PROFILE_SUCCESS = 'LOAD_MORE_POSTS_REQUESTED_PROFILE_SUCCESS';
export const LOAD_MORE_POSTS_REQUESTED_PROFILE_FAIL = 'LOAD_MORE_POSTS_REQUESTED_PROFILE_FAIL';
