export const POST_NEW_POST_START = 'POST_NEW_POST_START';
export const POST_NEW_POST_SUCCESS = 'POST_NEW_POST_SUCCESS';
export const POST_NEW_POST_FAIL = 'POST_NEW_POST_FAIL';

export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const DISLIKE_POST_FAIL = 'DISLIKE_POST_FAIL';

export const CREATE_COMMENT_FOR_POST_SUCCESS = 'CREATE_COMMENT_FOR_POST_SUCCESS';
export const CREATE_COMMENT_FOR_POST_FAIL = 'CREATE_COMMENT_FOR_POST_FAIL';
